spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seubanco
    username: seuuser
    password: suasenha
    # se for R2DBC:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/seubanco
    username: seuuser
    password: suasenha

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
